### ISSUE TITLE
getlongestrepeatedsubstring doesn't work as expected on "CAAAABDAAAABD"

### ISSUE THREAD

**Issue by rainwala** [wherrera10/SuffixTrees.jl#2]
getlongestrepeatedsubstring returns "AAA" instead of "AAAABD" for the string "CAAAABDAAAABD"

**Comment by wherrera10** [comment]
You need to add the "\$" terminator (Char '$') to the end.  Added to the tests.

	tests = [
		("CAAAABAAAABD\$", "AAAAB"),
		("GEEKSFORGEEKS\$", "GEEKS"),
		("AAAAAAAAAA\$", "AAAAAAAAA"),
		("ABCDEFG\$", ""),
		("ABABABA\$", "ABABA"),
		("ATCGATCGA\$", "ATCGA"),
		("banana\$", "ana"),
		("abcpqrabpqpq\$", "ab (or) pq"),
		("pqrpqpqabab\$", "ab (or) pq"),
		("CAAAABDAAAABD\$", "AAAABD"),
		("CAAAABDAAAABD", "AAA"),

	]
	println("Longest Repeated Substring in:\n")
	for (test, ans) in tests
		st = SuffixTree(test)
		@show getlongestrepeatedsubstring(st) == ans
	end


Passes all.

**Comment by wherrera10** [comment]
I will update with a change in the constructor for SuffixTree: add a default to add a terminator so that this issue will not arise for you when you leave off the terminator.

**Comment by wherrera10** [comment]
See https://github.com/wherrera10/SuffixTrees.jl/commit/2c5495957e0129180d50beb2d9383c6fe000bd5b
